### ISSUE TITLE
I need help with how to use it

### ISSUE THREAD

**Issue by wilmab123** [Naozumi520/Remedy#15]
I am having problems using it. I have installed it correctly and I can open it and start to costumize the overlays but I can't seem to get any further than that.

I am not very technical but I would love for this to work so I think I might need som help.

When I am done customizing and click ctrl ^ enter nothing happens, I am using the newest Standard Version

<img width="1280" alt="Skärmavbild 2023-03-25 kl  20 52 39" src="https://user-images.githubusercontent.com/128932514/227738620-0ced693b-5e5b-4b79-b611-cd001b4eca5d.png">

This is as far as I manage to go

**Comment by Naozumi520** [comment]
Hi! Sorry about that the issue was due to my outdated code, I haven't update Standard version for long time. But now I have sync both logics between Pro and Standard, also updated the code.

Please try [https://github.com/Naozumi520/Remedy/releases/tag/RemedyStandard1.1.2](1.1.2), I've fixed all the issues in this version.

And yes, the way you're doing is correct, it should now work on 1.1.2
