### ISSUE TITLE
Feature Request: Detect which VC your in + Change location of overlay widget

### ISSUE THREAD

**Issue by iCraft85** [Naozumi520/Remedy#3]
Is it possible to make the app detect if your in a voice call and if you are it will only then display the widget and will display the widget for that voice, also is it possible to add an ability to change the location of the widget?

**Comment by Naozumi520** [comment]
More research needed 😋
I'll see if it's possible to catch the info from the discord app

**Comment by kailred** [comment]
Seconding this! Thanks so much for this, it runs simply and easily. I would love to be able to adjust the position of the overlay, currently it defaults to the top left corner of my laptop screen, and I would like to be able to move it to my second monitor.

Thanks again for this!

**Comment by Naozumi520** [comment]
Sorry for not replying for a long time, because I have been very busy these days with the school stuffs and other things.
So after some research, the only way I found to detect if user joined a channel is logging in with discord.js with a user token. However, it could against the Discord TOS as it's part of selfbot. But as but as far as I know there's no such things like detect selfbot hosting and things like betterDiscord. In other hand the code I've test is only related to voiceStateUpdate and won't send any messages. [I've recorded a video](https://www.youtube.com/watch?v=J_CxB91HFtE) and please let me know if it's a good way to go and  could be accepted.

And for kailred's request I'm afraid that I can't do much about it because I have no idea how to let the user specific the position yet. Please let know if you have any ideas for it.

And thank you for liking my project, I didn't even know it could be better as first I just made it to compensate for the inconvenience I got while streaming on macOS 😋

I'll keep updating if I make any progress!

**Comment by iCraft85** [comment]
So with your first point, I don't really know much about how you would check any other way appart from that so I can't really help with that but with your second point I would like to know how you are setting the position of the overlay cuz if your doing it based on a coordinate system then you could have like 2 little boxes which let you tweak the X and Y coordinate which in my opinion is not the most elegant solution but it is a solution none the less.

**Comment by Naozumi520** [comment]
😆I've created a method to allow you pin the overlay to anywhere even in the second monitor!
<img width="150" alt="螢幕截圖 2022-07-12 下午3 44 56" src="https://user-images.githubusercontent.com/52615455/178436911-ccab0d89-3fef-43ce-80a7-a34ac2723da7.png">

In the future version you could Unpin the overlay and drag it to to the place you want for. After that just switch it back to "Pin" then it will always in the place u pinned for even relaunch the application!

**Comment by kailred** [comment]
thank you for your hard work! keep it up!

**Comment by Naozumi520** [comment]
Thanks! I've just release the new version! Please let me know if it's working properly.

**Comment by Naozumi520** [comment]
Close as required feature was added. Reopen this request if you encounter any issues.
